<footer class="footer">
	<div class="container">
		
		<!-- Newsletter -->

		<div class="newsletter">
			<div class="row">
				<div class="col">
					<div class="section_title text-center">
						<h1>Subscribe to newsletter</h1>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col text-center">
					<div class="newsletter_form_container mx-auto">
						<form action="https://colorlib.com/preview/theme/course/post">
							<div class="newsletter_form d-flex flex-md-row flex-column flex-xs-column align-items-center justify-content-center">
								<input id="newsletter_email" class="newsletter_email" type="email" placeholder="Email Address" required="required" data-error="Valid email is required.">
								<button id="newsletter_submit" type="submit" class="newsletter_submit_btn trans_300" value="Submit">Subscribe</button>
							</div>
						</form>
					</div>
				</div>
			</div>

		</div>

		<!-- Footer Content -->

		<div class="footer_content">
			<div class="row">

				<!-- Footer Column - About -->
				<div class="col-lg-4 footer_col">

					<!-- Logo -->
					<div class="logo_container">
						<div class="logo">
							<img src="./Course_files/logo.png" alt="">
							<span>White House</span>
						</div>
					</div>

					<p class="footer_about_text">In aliquam, augue a gravida rutrum, ante nisl fermentum nulla, vitae tempor nisl ligula vel nunc. Proin quis mi malesuada, finibus tortor fermentum, tempor lacus.</p>

				</div>

				<!-- Footer Column - Menu -->

				<div class="col-lg-2 footer_col">
					<div class="footer_column_title">Menu</div>
					<div class="footer_column_content">
						<ul>
							<li class="footer_list_item"><a href="./Home.html">Home</a></li>
							<li class="footer_list_item"><a href="./Courses.html">Courses</a></li>
							<li class="footer_list_item"><a href="#">Instractor</a></li>
							<li class="footer_list_item"><a href="./News.html">News</a></li>
							<li class="footer_list_item"><a href="./Contact.html">Contact</a></li>
						</ul>
					</div>
				</div>

				<!-- Footer Column - Usefull Links -->

				<div class="col-lg-2 footer_col">
					<div class="footer_column_title">Usefull Links</div>
					<div class="footer_column_content">
						<ul>
							<li class="footer_list_item"><a href="#">Facebook</a></li>
							<li class="footer_list_item"><a href="#">Twitter</a></li>
							<li class="footer_list_item"><a href="#">Youtube</a></li>
							<li class="footer_list_item"><a href="#">Instagram</a></li>
							
						</ul>
					</div>
				</div>

				<!-- Footer Column - Contact -->

				<div class="col-lg-4 footer_col">
					<div class="footer_column_title">Contact</div>
					<div class="footer_column_content">
						<ul>
							<li class="footer_contact_item">
								<div class="footer_contact_icon">
									<img src="./Course_files/placeholder.svg" alt="https://www.flaticon.com/authors/lucy-g">
								</div>
								23St, Botros from Tharwat in front of alqased  School , Tanta, Egypt 
							</li>
							<li class="footer_contact_item">
								<div class="footer_contact_icon">
									<img src="./Course_files/smartphone.svg" alt="https://www.flaticon.com/authors/lucy-g">
								</div>
								01011050094
							</li>
							<li class="footer_contact_item">
								<div class="footer_contact_icon">
									<img src="./Course_files/envelope.svg" alt="https://www.flaticon.com/authors/lucy-g">
								</div>WhiteHouseAcademy@gmail.com
							</li>
						</ul>
					</div>
				</div>

			</div>
		</div>

		<!-- Footer Copyright -->

		<div class="footer_bar d-flex flex-column flex-sm-row align-items-center">
			<div class="footer_copyright">
				<span><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					Copyright ©2018 All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by Essam Abozaid
					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
				</span>
			</div>
			
		</div>

	</div>
</footer>