<div class="services page_section">
					
					<div class="container">
						<div class="row">
							<div class="col">
								<div class="section_title text-center">
									<h1><?php echo lang('OUR SERVICES');?></h1>
								</div>
							</div>
						</div>

						<div class="row services_row">

							<div class="col-lg-4 service_item text-left d-flex flex-column align-items-start justify-content-start">
								<div class="icon_container d-flex flex-column justify-content-end">
									<img src="layout/images/earth-globe.svg" alt="">
								</div>
								<h3><?php echo lang('ONLINE COURSES');?></h3>
								<p><?php echo lang('ONLINE COURSES PARA');?></p>
							</div>

							<div class="col-lg-4 service_item text-left d-flex flex-column align-items-start justify-content-start">
								<div class="icon_container d-flex flex-column justify-content-end">
									<img src="layout/images/exam.svg" alt="">
								</div>
								<h3><?php echo lang('INDOOR COURSES');?></h3>
								<p><?php echo lang('INDOOR COURSES PARA');?></p>
							</div>

							<div class="col-lg-4 service_item text-left d-flex flex-column align-items-start justify-content-start">
								<div class="icon_container d-flex flex-column justify-content-end">
									<img src="layout/images/books.svg" alt="">
								</div>
								<h3><?php echo lang('AMAZING LIBRARY');?></h3>
								<p><?php echo lang('AMAZING LIBRARY PARA');?></p>
							</div>

							<div class="col-lg-4 service_item text-left d-flex flex-column align-items-start justify-content-start">
								<div class="icon_container d-flex flex-column justify-content-end">
									<img src="layout/images/professor.svg" alt="">
								</div>
								<h3><?php echo lang('EXCEPTIONAL PROFESSORS');?></h3>
								<p><?php echo lang('EXCEPTIONAL PROFESSORS PARA');?></p>
							</div>

							<div class="col-lg-4 service_item text-left d-flex flex-column align-items-start justify-content-start">
								<div class="icon_container d-flex flex-column justify-content-end">
									<img src="layout/images/blackboard.svg" alt="">
								</div>
								<h3><?php echo lang('ARABITRATION COURSES');?></h3>
								<p><?php echo lang('ARABITRATION COURSES PARA');?></p>
							</div>

							<div class="col-lg-4 service_item text-left d-flex flex-column align-items-start justify-content-start">
								<div class="icon_container d-flex flex-column justify-content-end">
									<img src="layout/images/mortarboard.svg" alt="">
								</div>
								<h3><?php echo lang('GRADUATE CERTIFICATES');?></h3>
								<p><?php echo lang('GRADUATE CERTIFICATES PARA');?></p>
							</div>

						</div>
					</div>
				</div>